version: '3'

services:
  FleetManager.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  VehicleTracker.API:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  statusgenerator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


